### ISSUE TITLE
Promotion (HA)

### ISSUE THREAD

**Issue by zheliazkov** [LINBIT/drbd-reactor#1]
I'm installing Linstor on CentOS7 and making HA Controller.
I have 3 disk nodes that the linstor database resource is placed as written in the guide/documentation.
If I stop one of the machines the drbd storage is ok but in the logs of the machine it tries to mount the database resource on both of the machines.
If I stop parallel two of the machines - the resource is never recovering and the drbd status says all the nodes are diskless.

The one that isn't rebooted:
linstor_db role:Secondary
  disk:Diskless quorum:no
  node-2 connection:Connecting
  node-3 connection:Connecting

The other two:
linstor_db role:Secondary
  disk:Diskless quorum:no
  node-2 connection:StandAlone
  node-3 connection:StandAlone

linstor_db role:Secondary
  disk:Diskless quorum:no
  node-1 connection:StandAlone
  node-2 connection:StandAlone

What should be the problem? :/

Thanks in advance.

**Comment by rck** [comment]
> I'm installing Linstor on CentOS7 and making HA Controller.
> I have 3 disk nodes that the linstor database resource is placed as written in the guide/documentation.
> If I stop one of the machines the drbd storage is ok but in the logs of the machine it tries to mount the database resource on both of the machines.

That is expected and perfectly fine. The old is gone, you have 2 left (== quorum) they race to become Primary by mounting the FS. One wins, the other does not, but both try. All good.

> If I stop parallel two of the machines - the resource is never recovering and the drbd status says all the nodes are diskless.

If you don't have quorum you can not become Primary, that is the whole idea of avoiding split brains via quorum. Also expected. That nodes are Diskless is weird, I will discuss that internally. An exact step by step reproducer would be great. What are the drbdd configs, what was the state of the DRBD storage, where was the LINSTOR controller started, which node did you stop, serial or parallel, how did you stop them,... So far this is a bit too much "does not work" without any information on how to reproduce it.

**Comment by zheliazkov** [comment]
> > I'm installing Linstor on CentOS7 and making HA Controller.
> > I have 3 disk nodes that the linstor database resource is placed as written in the guide/documentation.
> > If I stop one of the machines the drbd storage is ok but in the logs of the machine it tries to mount the database resource on both of the machines.
> 
> That is expected and perfectly fine. The old is gone, you have 2 left (== quorum) they race to become Primary by mounting the FS. One wins, the other does not, but both try. All good.
> 
> > If I stop parallel two of the machines - the resource is never recovering and the drbd status says all the nodes are diskless.
> 
> If you don't have quorum you can not become Primary, that is the whole idea of avoiding split brains via quorum. Also expected. That nodes are Diskless is weird, I will discuss that internally. An exact step by step reproducer would be great. What are the drbdd configs, what was the state of the DRBD storage, where was the LINSTOR controller started, which node did you stop, serial or parallel, how did you stop them,... So far this is a bit too much "does not work" without any information on how to reproduce it.

Thanks for the help. 

> What are the drbdd configs?

The drbdd is configured as follow on all the machines:
```
[[promoter]]
[promoter.resources.linstor_db]
start = ["var-lib-linstor.mount", "linstor-controller.service"]
```
> What was the state of the DRBD storage?

Before that happened, as seen with the linstor client - the resource and its drive was UpToDate
> Where was the LINSTOR controller started?

The controller was first created on the first machine (colo-srv-1/node-1) to be able to make its database and make it distributed as seen in the manual.
>  Which node did you stop, serial or parallel, how did you stop them?

I've rebooted two of the machines parallel while the linstor says all are UpToDate and after that I was waiting they to reassemble the storage after they boot. 
I've experienced this not just once. 

I see that the one that isn't rebooted (colo-srv-1) says that the resource is diskless and no connection to the others.

The versions that I've used are:
```
DRBDADM_BUILDTAG=GIT-hash:\ a7820b3c14497a34f955ba5ce56cf1bc9d2d353e\ build\ by\ root@colo-srv-3\,\ 2021-04-13\ 12:41:32
DRBDADM_API_VERSION=2
DRBD_KERNEL_VERSION_CODE=0x09001c
DRBD_KERNEL_VERSION=9.0.28
DRBDADM_VERSION_CODE=0x091000
DRBDADM_VERSION=9.16.0
```
The packages are were downloaded from the official website tarball download page and running in `CentOS7 3.10.0-1160.24.1.el7.x86_64`:
```
drbd-9.0.28-1
drbd-utils-9.16.0
linstor-server-1.11.1
python-linstor-1.6.0
linstor-client-1.6.1
drbdd-0.2.0.tar.gz
```

Thanks in advance.

BR,
Plamen

**Comment by rck** [comment]
> I've rebooted two of the machines parallel while the linstor says all are UpToDate and after that I was waiting they to reassemble the storage after they boot.
> I've experienced this not just once.
> 
> I see that the one that isn't rebooted (colo-srv-1) says that the resource is diskless and no connection to the others.

just to make that somehow reproducible: the node you did not reboot was the one the service was running on? Or was the "active node" one of those you rebooted?

What is just weird is that a node, even the one you did not reboot, becomes diskless. If that would be common, believe me, many people would tell us... What is your backing storage? Maybe it goes down when the other nodes go down and DRBD simply has to go diskless because it has to detach because the backing device goes away? What I would do:

- check the kernel logs around the time this happens. There should be some indication why the resources goes diskless
- try to reproduce it manually: create a new resource on all 3 nodes (manually or via LINSTOR), bring it up, make 1 primary, reboot 2 nodes, check if the resource is now diskless. Start and understand the lower level, this most likely is something in your system, it might - I'm pretty sure it isn't - a DRBD bug only you trigger, it most certainly is not a drbdd bug.

**Comment by zheliazkov** [comment]
> > I've rebooted two of the machines parallel while the linstor says all are UpToDate and after that I was waiting they to reassemble the storage after they boot.
> > I've experienced this not just once.
> > I see that the one that isn't rebooted (colo-srv-1) says that the resource is diskless and no connection to the others.
> 
> just to make that somehow reproducible: the node you did not reboot was the one the service was running on? Or was the "active node" one of those you rebooted?
> 
> What is just weird is that a node, even the one you did not reboot, becomes diskless. If that would be common, believe me, many people would tell us... What is your backing storage? Maybe it goes down when the other nodes go down and DRBD simply has to go diskless because it has to detach because the backing device goes away? What I would do:
> 
> * check the kernel logs around the time this happens. There should be some indication why the resources goes diskless
> * try to reproduce it manually: create a new resource on all 3 nodes (manually or via LINSTOR), bring it up, make 1 primary, reboot 2 nodes, check if the resource is now diskless. Start and understand the lower level, this most likely is something in your system, it might - I'm pretty sure it isn't - a DRBD bug only you trigger, it most certainly is not a drbdd bug.

**Thank you very much for your time and response!**

I've made the whole cluster as new as you advice.
Before the two node removal test, I've rebooted 2 times the running controllers to test that it switches without problem - It looks good.
But with parallel rebooting of two of the machines something similar happened:

> just to make that somehow reproducible: the node you did not reboot was the one the service was running on? Or was the "active node" one of those you rebooted?

Now I've rebooted parallel the two non-controller machines.

> What is your backing storage?

LVM volume group with ext4 volume on all the nodes.

> Try to reproduce it manually: create a new resource on all 3 nodes (manually or via LINSTOR), bring it up, make 1 primary, reboot 2 nodes, check if the resource is now diskless.

I've done it. At the time of the rebooting, non-rebooted **colo-srv-3** (primary/crontroller) node is loosing its quorum and become secondary as the log reported:
```
апр 21 13:59:30 colo-srv-3 Controller[42579]: 13:59:30.194 [SslConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /192.168.25.2:3366 has closed the connection.
апр 21 13:59:33 colo-srv-3 Controller[42579]: 13:59:33.188 [SslConnector] INFO  LINSTOR/Controller - SYSTEM - Remote satellite peer /192.168.25.1:3366 has closed the connection.
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: PingAck did not arrive in time.
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: conn( Connected -> NetworkFailure ) peer( Secondary -> Unknown )
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db/0 drbd1000 colo-srv-1: pdsk( UpToDate -> DUnknown ) repl( Established -> Off )
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: ack_receiver terminated
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: Terminating ack_recv thread
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: PingAck did not arrive in time.
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: conn( Connected -> NetworkFailure ) peer( Secondary -> Unknown )
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db/0 drbd1000: quorum( yes -> no )
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db/0 drbd1000 colo-srv-2: pdsk( UpToDate -> DUnknown ) repl( Established -> Off )
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: ack_receiver terminated
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: Terminating ack_recv thread
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db/0 drbd1000: helper command: /sbin/drbdadm quorum-lost
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: Restarting sender thread
апр 21 13:59:39 colo-srv-3 drbdd[40539]: INFO [drbdd::plugin::promoter] promoter: resource 'linstor_db' lost quorum
апр 21 13:59:39 colo-srv-3 drbdd[40539]: INFO [drbdd::plugin::promoter] promoter: systemctl stop linstor-controller.service
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db/0 drbd1000: helper command: /sbin/drbdadm quorum-lost exit code 0
апр 21 13:59:39 colo-srv-3 systemd[1]: Stopping LINSTOR Controller Service...
апр 21 13:59:39 colo-srv-3 Controller[42579]: 13:59:39.154 [Thread-3] INFO  LINSTOR/Controller - SYSTEM - Shutdown in progress
апр 21 13:59:39 colo-srv-3 Controller[42579]: 13:59:39.158 [Thread-3] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'GrizzlyHttpServer' of type Grizzly-HTTP-Server
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: Restarting sender thread
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: Connection closed
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: helper command: /sbin/drbdadm disconnected
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: helper command: /sbin/drbdadm disconnected exit code 0
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: conn( NetworkFailure -> Unconnected )
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: Restarting receiver thread
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-1: conn( Unconnected -> Connecting )
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: Connection closed
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: helper command: /sbin/drbdadm disconnected
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: helper command: /sbin/drbdadm disconnected exit code 0
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: conn( NetworkFailure -> Unconnected )
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: Restarting receiver thread
апр 21 13:59:39 colo-srv-3 kernel: drbd linstor_db colo-srv-2: conn( Unconnected -> Connecting )
апр 21 13:59:39 colo-srv-3 Controller[42579]: 13:59:39.383 [Thread-3] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'GrizzlyHttpServer' to complete shutdown
апр 21 13:59:39 colo-srv-3 Controller[42579]: 13:59:39.403 [Thread-3] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TaskScheduleService' of type TaskScheduleService
апр 21 13:59:39 colo-srv-3 Controller[42579]: 13:59:39.403 [Thread-3] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TaskScheduleService' to complete shutdown
апр 21 13:59:42 colo-srv-3 Controller[42579]: 13:59:42.403 [Thread-3] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'DatabaseService' of type DatabaseService
апр 21 13:59:42 colo-srv-3 Controller[42579]: 13:59:42.404 [Thread-3] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'DatabaseService' to complete shutdown
апр 21 13:59:42 colo-srv-3 Controller[42579]: 13:59:42.404 [Thread-3] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TimerEventService' of type TimerEventService
апр 21 13:59:42 colo-srv-3 Controller[42579]: 13:59:42.404 [Thread-3] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TimerEventService' to complete shutdown
апр 21 13:59:44 colo-srv-3 kernel: Aborting journal on device drbd1000-8.
апр 21 13:59:44 colo-srv-3 kernel: Buffer I/O error on dev drbd1000, logical block 131072, lost sync page write
апр 21 13:59:44 colo-srv-3 kernel: JBD2: Error -5 detected when updating journal superblock for drbd1000-8.
апр 21 13:59:52 colo-srv-3 Controller[42579]: 13:59:52.404 [Thread-3] INFO  LINSTOR/Controller - SYSTEM - Shutdown complete
апр 21 13:59:52 colo-srv-3 systemd[1]: Stopped LINSTOR Controller Service.
апр 21 13:59:52 colo-srv-3 drbdd[40539]: INFO [drbdd::plugin::promoter] promoter: systemctl stop var-lib-linstor.mount
апр 21 13:59:52 colo-srv-3 systemd[1]: Unmounting Filesystem for the LINSTOR controller...
апр 21 13:59:52 colo-srv-3 kernel: Buffer I/O error on dev drbd1000, logical block 0, lost sync page write
апр 21 13:59:52 colo-srv-3 systemd[1]: Unmounted Filesystem for the LINSTOR controller.
апр 21 13:59:52 colo-srv-3 kernel: drbd linstor_db: role( Primary -> Secondary )
```
This time the non-rebooted last active node **colo-srv-3** doesn't became diskless.
After the two rebooted node became up, drbd statuses was the following:
```
[root@colo-srv-1 ~]# drbdadm status
linstor_db role:Secondary
  disk:Diskless quorum:no
  colo-srv-2 connection:StandAlone
  colo-srv-3 connection:StandAlone

[root@colo-srv-2 linstor-satellite]# drbdadm status
linstor_db role:Secondary
  disk:Diskless quorum:no
  colo-srv-1 connection:StandAlone
  colo-srv-3 connection:StandAlone

[root@colo-srv-3 ~]# drbdadm status
linstor_db role:Secondary
  disk:UpToDate quorum:no
  colo-srv-1 connection:Connecting
  colo-srv-2 connection:Connecting
```
I've looked again in the rebooted machine **colo-srv-2** logs and find the following:
```
апр 21 14:01:45 colo-srv-2 systemd[1]: Configuration file /usr/lib/systemd/system/drbdd.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
апр 21 14:01:45 colo-srv-2 kernel: drbd: loading out-of-tree module taints kernel.
апр 21 14:01:45 colo-srv-2 kernel: drbd: module verification failed: signature and/or required key missing - tainting kernel
апр 21 14:01:45 colo-srv-2 kernel: drbd: initialized. Version: 9.0.28-1 (api:2/proto:86-119)
апр 21 14:01:45 colo-srv-2 kernel: drbd: GIT-hash: 8db03a6344e74e5c160294d80188dc31b785db61 build by root@colo-srv-2, 2021-04-16 12:44:58
апр 21 14:01:45 colo-srv-2 kernel: drbd: registered as block device major 147
апр 21 14:01:45 colo-srv-2 systemd-modules-load[2191]: Inserted module 'drbd'
апр 21 14:01:45 colo-srv-2 systemd-modules-load[2191]: Inserted module 'drbd_transport_tcp'
апр 21 14:01:45 colo-srv-2 kernel: drbd linstor_db: Starting worker thread (from drbdsetup [2628])
апр 21 14:01:45 colo-srv-2 kernel: drbd linstor_db colo-srv-1: Starting sender thread (from drbdsetup [2635])
апр 21 14:01:45 colo-srv-2 kernel: drbd linstor_db colo-srv-3: Starting sender thread (from drbdsetup [2638])
апр 21 14:01:45 colo-srv-2 drbdd[2602]: open(/dev/vg_nvme/linstor_db_00000) failed: No such file or directory
апр 21 14:01:45 colo-srv-2 drbdd[2602]: Command 'drbdmeta 1000 v09 /dev/vg_nvme/linstor_db_00000 internal apply-al' terminated with exit code 20
апр 21 14:01:45 colo-srv-2 drbdd[2602]: WARN [drbdd::plugin::promoter] promoter: 'drbdadm adjust linstor_db' did not return successfully
апр 21 14:01:45 colo-srv-2 drbdd[2602]: WARN [drbdd::events] backing device information will be missing!
```

I've checked again that the **/dev/vg_nvme/linstor_db_00000** is located on the node - it is there, but not sure what triggers  **WARN [drbdd::events] backing device information will be missing!** and is this the problem :/

Thanks in advance again!

BR,
Plamen

**Comment by rck** [comment]
> I've checked again that the /dev/vg_nvme/linstor_db_00000 is located on the node - it is there

I'd assume it is there "now", but was not at that time. Looks like drbdd (drbd-reactor nowadays) races here with LVM/udev that did not have enough time to create the symlink. I will look into that and see if we can somehow avoid that.

> WARN [drbdd::events] backing device information will be missing!

That just means that you don't have backing_device info in the `drbdsetup events2` stream. Completely unrelated and harmless in this case, not releated to your missing backing device.

**Comment by rck** [comment]
I'm pretty sure that the VG was not active or udev had not have time to create the links. It is relatively easy to get the backing device names from the resource name and wait with the `drbdadm adjust` until the backing devices show up. I will add that soon

**Comment by zheliazkov** [comment]
> I'm pretty sure that the VG was not active or udev had not have time to create the links. It is relatively easy to get the backing device names from the resource name and wait with the `drbdadm adjust` until the backing devices show up. I will add that soon

Thanks for the help Roland.

I've made the service to wait and there is no problem.

Best wishes,
Plamen

**Comment by rck** [comment]
I'm pretty sure that the VG was not active or udev had not have time to create the links. It is relatively easy to get the backing device names from the resource name and wait with the `drbdadm adjust` until the backing devices show up. I will add that soon

**Comment by rck** [comment]
for devices with a backing device (i.e., not diskless) the promoter plugin now waits until the device is ready: d9674bf9d75276ea135472cfbf5e972bc9efc8d3
