### ISSUE TITLE
Plugin IDs showing as '<none>'

### ISSUE THREAD

**Issue by acidrop** [LINBIT/drbd-reactor#2]
I'm testing the latest version of drbd-reactor. I've created 2 plugins (promoter and prometheus). For some reason their IDs are showing as "none". Is this a syntax error on my side or a bug ?

> root@pve1:~# drbd-reactorctl
> Prometheus (ID: '<none>') listening on 10.1.2.12:9942
> Promoter (ID: '<none>')
> Most likely active on node "pve3"
> drbd-services@linstor_db.target
> ● ├─drbd-promote@linstor_db.service
> ● ├─linstor-controller.service
> ● └─var-lib-linstor.mount

> root@pve1:~# drbd-reactorctl ls
> /etc/drbd-reactor.d/prometheus.toml
> Prometheus (ID: '<none>')
> /etc/drbd-reactor.d/linstor-ha.toml
> Promoter (ID: '<none>')

> root@pve1:~# drbd-reactorctl cat
> /etc/drbd-reactor.d/prometheus.toml:
> id = "prometheus"
> [[prometheus]]
> enums = true
> address = "10.1.2.12:9942"
> /etc/drbd-reactor.d/linstor-ha.toml:
> id = "linstorha"
> [[promoter]]
> [promoter.resources.linstor_db]
> start = ["var-lib-linstor.mount", "linstor-controller.service"]

**Comment by WanzenBug** [comment]
Hi!

You'll want to write `id` in the plugins section like this:
```
[[prometheus]]
id = "prometheus"
enums = true
address = "10.1.2.12:9942"

[[promoter]]
id = "linstorha"
[promoter.resources.linstor_db]
start = ["var-lib-linstor.mount", "linstor-controller.service"]
```

**Comment by acidrop** [comment]
Makes sense... thanks for the tip!
