### ISSUE TITLE
Maintenance mode - smooth failover

### ISSUE THREAD

**Issue by aellert** [LINBIT/drbd-reactor#3]
I don't know if this is a linstor limitation or misunderstanding by myself ( https://github.com/LINBIT/linstor-server/issues/261), but I can't find a procedure to smoothly take a node off my cluster and do some maintenance.

I use drbd-reactor with linstor NFS gateway and actually if I do:
```
drbd-reactorctl disable
```
the DRBD resources on that node become Secondary (which is what I want) but NFS clients actually connected get stucked and NFS shares are not available for them. Whereas the failover seems to  have worked fine, only new NFS mount succeed (or remount / reboot previously connected NFS clients)

**Comment by rck** [comment]
@chrboe still anything you can contribute to that? got that fixed?
