### ISSUE TITLE
Unable to bring up linstor controller, after upgrading to the latest version

### ISSUE THREAD

**Issue by acidrop** [LINBIT/drbd-reactor#8]
After upgrading to the latest version of drbd-reactor and linstor-controller, reactor fails to bring up linstor-controller. I'm able to bring up the controller (on all 3 nodes) manually with drbd-reactor disabled.

Could you please check if this is reproducible on your side as well ?

>drbd-dkms                             9.2.1-1ppa1~focal1
>drbd-reactor                          0.10.2-1ppa1~focal1 
> idrbd-utils                            9.22.0-1ppa1~focal1 

> linstor-client                        1.16.0-1ppa1~focal1 
> linstor-common                        1.20.1-1ppa1~focal1
> linstor-controller                    1.20.1-1ppa1~focal1
> python-linstor                        1.16.0-1ppa1~focal1

> Dec 15 11:25:11 linctrl03 systemd[1]: Reloading DRBD-Reactor Service.
> Dec 15 11:25:11 linctrl03 systemd[1]: Reloaded DRBD-Reactor Service.
> Dec 15 11:25:11 linctrl03 sshd[7396]: Received disconnect from 10.10.12.8 port 56708:11: disconnected by user
> Dec 15 11:25:11 linctrl03 sshd[7396]: Disconnected from user root 10.10.12.8 port 56708
> Dec 15 11:25:11 linctrl03 systemd[1]: session-33.scope: Succeeded.
> Dec 15 11:25:11 linctrl03 sshd[7396]: pam_unix(sshd:session): session closed for user root
> Dec 15 11:25:11 linctrl03 systemd-logind[692]: Session 33 logged out. Waiting for processes to exit.
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] adjust_resources: waiting for backing device '/dev/ubuntu-vg/linstor_db' to become ready
> Dec 15 11:25:11 linctrl03 systemd-logind[692]: Removed session 33.
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] adjust_resources: backing device '/dev/ubuntu-vg/linstor_db' now ready
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] Checking DRBD options for resource 'linstor_db'
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: WARN [drbd_reactor::plugin::promoter] resource 'linstor_db': DRBD option 'on-suspended-primary-outdated' should be 'force-secondary', but is 'disconnect'
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_write_unit: creating "/run/systemd/system/drbd-promote@linstor_db.service.d/reactor.conf"
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_write_unit: creating "/run/systemd/system/drbd-demote-or-escalate@linstor_db.service.d/reactor.conf"
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_write_unit: creating "/run/systemd/system/var-lib-linstor.mount.d/reactor-50-mount.conf"
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_write_unit: creating "/run/systemd/system/var-lib-linstor.mount.d/reactor.conf"
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_write_unit: creating "/run/systemd/system/linstor-controller.service.d/reactor.conf"
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_write_unit: creating "/run/systemd/system/drbd-services@linstor_db.target.d/reactor.conf"
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_write_unit: creating "/run/systemd/system/drbd-services@linstor_db.target.d/reactor-50-before.conf"
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_daemon_reload: reloading daemon
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin] system: sh -c systemctl daemon-reload
> Dec 15 11:25:11 linctrl03 systemd[1]: Reloading.
> Dec 15 11:25:11 linctrl03 kernel: drbd linstor_db linctrl02: Preparing remote state change 2101683609
> Dec 15 11:25:11 linctrl03 kernel: drbd linstor_db linctrl02: Committing remote state change 2101683609 (primary_nodes=2)
> Dec 15 11:25:11 linctrl03 kernel: drbd linstor_db linctrl02: peer( Secondary -> Primary )
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] run: resource 'linstor_db' may promote after 0ms
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_start: systemctl start drbd-services@linstor_db.target
> Dec 15 11:25:11 linctrl03 systemd[1]: Mounting drbd-reactor controlled var-lib-linstor...
> Dec 15 11:25:11 linctrl03 mount[7533]: mount: /var/lib/linstor: mount(2) system call failed: Wrong medium type.
> Dec 15 11:25:11 linctrl03 systemd[1]: var-lib-linstor.mount: Mount process exited, code=exited, status=32/n/a
> Dec 15 11:25:11 linctrl03 systemd[1]: var-lib-linstor.mount: Failed with result 'exit-code'.
> Dec 15 11:25:11 linctrl03 drbd-reactor[7532]: A dependency job for drbd-services@linstor_db.target failed. See 'journalctl -xe' for details.
> Dec 15 11:25:11 linctrl03 systemd[1]: Failed to mount drbd-reactor controlled var-lib-linstor.
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] stop_actions (could trigger failure actions (e.g., reboot)): linstor_db
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] stop_actions: stopping 'drbd-services@linstor_db.target'
> Dec 15 11:25:11 linctrl03 systemd[1]: Dependency failed for Services for DRBD resource linstor_db.
> Dec 15 11:25:11 linctrl03 systemd[1]: drbd-services@linstor_db.target: Job drbd-services@linstor_db.target/start failed with result 'dependency'.
> Dec 15 11:25:11 linctrl03 systemd[1]: Dependency failed for drbd-reactor controlled linstor-controller.
> Dec 15 11:25:11 linctrl03 systemd[1]: linstor-controller.service: Job linstor-controller.service/start failed with result 'dependency'.
> Dec 15 11:25:11 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_stop: systemctl stop drbd-services@linstor_db.target
> Dec 15 11:25:11 linctrl03 systemd[1]: Stopping Promotion of DRBD resource linstor_db...
> Dec 15 11:25:11 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Succeeded.
> Dec 15 11:25:11 linctrl03 systemd[1]: Stopped Promotion of DRBD resource linstor_db.
> Dec 15 11:25:21 linctrl03 kernel: drbd linstor_db linctrl02: Preparing remote state change 103241576
> Dec 15 11:25:21 linctrl03 kernel: drbd linstor_db linctrl02: Committing remote state change 103241576 (primary_nodes=0)
> Dec 15 11:25:21 linctrl03 kernel: drbd linstor_db linctrl02: peer( Primary -> Secondary )
> Dec 15 11:25:21 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] run: resource 'linstor_db' may promote after 0ms
> Dec 15 11:25:21 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_start: systemctl start drbd-services@linstor_db.target
> Dec 15 11:25:21 linctrl03 systemd[1]: Starting Promotion of DRBD resource linstor_db...
> Dec 15 11:25:21 linctrl03 kernel: drbd linstor_db linctrl02: Preparing remote state change 2755994662
> Dec 15 11:25:21 linctrl03 kernel: drbd linstor_db linctrl02: Committing remote state change 2755994662 (primary_nodes=2)
> Dec 15 11:25:21 linctrl03 kernel: drbd linstor_db linctrl02: peer( Secondary -> Primary )
> Dec 15 11:25:21 linctrl03 kernel: drbd linstor_db linctrl01: Preparing remote state change 3882556691
> Dec 15 11:25:21 linctrl03 kernel: drbd linstor_db linctrl01: Aborting remote state change 3882556691
> Dec 15 11:25:22 linctrl03 drbd-linstor_db[7554]: linstor_db: State change failed: (-1) Multiple primaries not allowed by config
> Dec 15 11:25:22 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Main process exited, code=exited, status=11/n/a
> Dec 15 11:25:22 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Failed with result 'exit-code'.
> Dec 15 11:25:22 linctrl03 systemd[1]: Failed to start Promotion of DRBD resource linstor_db.
> Dec 15 11:25:22 linctrl03 systemd[1]: Dependency failed for drbd-reactor controlled var-lib-linstor.
> Dec 15 11:25:22 linctrl03 drbd-reactor[7553]: A dependency job for drbd-services@linstor_db.target failed. See 'journalctl -xe' for details.
> Dec 15 11:25:22 linctrl03 systemd[1]: Dependency failed for Services for DRBD resource linstor_db.
> Dec 15 11:25:22 linctrl03 systemd[1]: drbd-services@linstor_db.target: Job drbd-services@linstor_db.target/start failed with result 'dependency'.
> Dec 15 11:25:22 linctrl03 systemd[1]: Dependency failed for drbd-reactor controlled linstor-controller.
> Dec 15 11:25:22 linctrl03 systemd[1]: linstor-controller.service: Job linstor-controller.service/start failed with result 'dependency'.
> Dec 15 11:25:22 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] stop_actions (could trigger failure actions (e.g., reboot)): linstor_db
> Dec 15 11:25:22 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] stop_actions: stopping 'drbd-services@linstor_db.target'
> Dec 15 11:25:22 linctrl03 systemd[1]: var-lib-linstor.mount: Job var-lib-linstor.mount/start failed with result 'dependency'.
> Dec 15 11:25:22 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Triggering OnFailure= dependencies.
> Dec 15 11:25:22 linctrl03 systemd[1]: Starting Demotion of DRBD resource linstor_db...
> Dec 15 11:25:22 linctrl03 drbd-linstor_db[7565]: about to demote (or escalate to the FailureAction)
> Dec 15 11:25:22 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_stop: systemctl stop drbd-services@linstor_db.target
> Dec 15 11:25:22 linctrl03 systemd[1]: drbd-demote-or-escalate@linstor_db.service: Succeeded.
> Dec 15 11:25:22 linctrl03 systemd[1]: Finished Demotion of DRBD resource linstor_db.
> Dec 15 11:25:36 linctrl03 kernel: drbd linstor_db linctrl02: Preparing remote state change 3160842494
> Dec 15 11:25:36 linctrl03 kernel: drbd linstor_db linctrl02: Committing remote state change 3160842494 (primary_nodes=0)
> Dec 15 11:25:36 linctrl03 kernel: drbd linstor_db linctrl02: peer( Primary -> Secondary )
> Dec 15 11:25:36 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] run: resource 'linstor_db' may promote after 0ms
> Dec 15 11:25:36 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_start: systemctl start drbd-services@linstor_db.target
> Dec 15 11:25:36 linctrl03 kernel: drbd linstor_db linctrl02: Preparing remote state change 822542183
> Dec 15 11:25:36 linctrl03 kernel: drbd linstor_db linctrl02: Committing remote state change 822542183 (primary_nodes=2)
> Dec 15 11:25:36 linctrl03 kernel: drbd linstor_db linctrl02: peer( Secondary -> Primary )
> Dec 15 11:25:36 linctrl03 systemd[1]: Starting Promotion of DRBD resource linstor_db...
> Dec 15 11:25:36 linctrl03 drbd-linstor_db[7575]: linstor_db: State change failed: (-1) Multiple primaries not allowed by config
> Dec 15 11:25:36 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Main process exited, code=exited, status=11/n/a
> Dec 15 11:25:36 linctrl03 drbd-reactor[7574]: A dependency job for drbd-services@linstor_db.target failed. See 'journalctl -xe' for details.
> Dec 15 11:25:36 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Failed with result 'exit-code'.
> Dec 15 11:25:36 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] stop_actions (could trigger failure actions (e.g., reboot)): linstor_db
> Dec 15 11:25:36 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] stop_actions: stopping 'drbd-services@linstor_db.target'
> Dec 15 11:25:36 linctrl03 systemd[1]: Failed to start Promotion of DRBD resource linstor_db.
> Dec 15 11:25:36 linctrl03 systemd[1]: Dependency failed for drbd-reactor controlled var-lib-linstor.
> Dec 15 11:25:36 linctrl03 systemd[1]: Dependency failed for Services for DRBD resource linstor_db.
> Dec 15 11:25:36 linctrl03 systemd[1]: drbd-services@linstor_db.target: Job drbd-services@linstor_db.target/start failed with result 'dependency'.
> Dec 15 11:25:36 linctrl03 systemd[1]: Dependency failed for drbd-reactor controlled linstor-controller.
> Dec 15 11:25:36 linctrl03 systemd[1]: linstor-controller.service: Job linstor-controller.service/start failed with result 'dependency'.
> Dec 15 11:25:36 linctrl03 systemd[1]: var-lib-linstor.mount: Job var-lib-linstor.mount/start failed with result 'dependency'.
> Dec 15 11:25:36 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Triggering OnFailure= dependencies.
> Dec 15 11:25:36 linctrl03 systemd[1]: Starting Demotion of DRBD resource linstor_db...
> Dec 15 11:25:36 linctrl03 drbd-linstor_db[7586]: about to demote (or escalate to the FailureAction)
> Dec 15 11:25:36 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_stop: systemctl stop drbd-services@linstor_db.target
> Dec 15 11:25:36 linctrl03 systemd[1]: drbd-demote-or-escalate@linstor_db.service: Succeeded.
> Dec 15 11:25:36 linctrl03 systemd[1]: Finished Demotion of DRBD resource linstor_db.
> Dec 15 11:25:51 linctrl03 kernel: drbd linstor_db linctrl02: Preparing remote state change 3838794161
> Dec 15 11:25:51 linctrl03 kernel: drbd linstor_db linctrl02: Committing remote state change 3838794161 (primary_nodes=0)
> Dec 15 11:25:51 linctrl03 kernel: drbd linstor_db linctrl02: peer( Primary -> Secondary )
> Dec 15 11:25:51 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] run: resource 'linstor_db' may promote after 0ms
> Dec 15 11:25:51 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_start: systemctl start drbd-services@linstor_db.target
> Dec 15 11:25:51 linctrl03 systemd[1]: Starting Promotion of DRBD resource linstor_db...
> Dec 15 11:25:51 linctrl03 kernel: drbd linstor_db linctrl02: Preparing remote state change 617163246
> Dec 15 11:25:51 linctrl03 kernel: drbd linstor_db linctrl02: Committing remote state change 617163246 (primary_nodes=2)
> Dec 15 11:25:51 linctrl03 kernel: drbd linstor_db linctrl02: peer( Secondary -> Primary )
> Dec 15 11:25:51 linctrl03 drbd-linstor_db[7598]: linstor_db: State change failed: (-1) Multiple primaries not allowed by config
> Dec 15 11:25:51 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Main process exited, code=exited, status=11/n/a
> Dec 15 11:25:51 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Failed with result 'exit-code'.
> Dec 15 11:25:51 linctrl03 systemd[1]: Failed to start Promotion of DRBD resource linstor_db.
> Dec 15 11:25:51 linctrl03 systemd[1]: Dependency failed for drbd-reactor controlled var-lib-linstor.
> Dec 15 11:25:51 linctrl03 systemd[1]: Dependency failed for Services for DRBD resource linstor_db.
> Dec 15 11:25:51 linctrl03 systemd[1]: drbd-services@linstor_db.target: Job drbd-services@linstor_db.target/start failed with result 'dependency'.
> Dec 15 11:25:51 linctrl03 systemd[1]: Dependency failed for drbd-reactor controlled linstor-controller.
> Dec 15 11:25:51 linctrl03 systemd[1]: linstor-controller.service: Job linstor-controller.service/start failed with result 'dependency'.
> Dec 15 11:25:51 linctrl03 systemd[1]: var-lib-linstor.mount: Job var-lib-linstor.mount/start failed with result 'dependency'.
> Dec 15 11:25:51 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Triggering OnFailure= dependencies.
> Dec 15 11:25:51 linctrl03 drbd-reactor[7597]: A dependency job for drbd-services@linstor_db.target failed. See 'journalctl -xe' for details.
> Dec 15 11:25:51 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] stop_actions (could trigger failure actions (e.g., reboot)): linstor_db
> Dec 15 11:25:51 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] stop_actions: stopping 'drbd-services@linstor_db.target'
> Dec 15 11:25:51 linctrl03 systemd[1]: Starting Demotion of DRBD resource linstor_db...
> Dec 15 11:25:51 linctrl03 drbd-linstor_db[7610]: about to demote (or escalate to the FailureAction)
> Dec 15 11:25:51 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_stop: systemctl stop drbd-services@linstor_db.target
> Dec 15 11:25:51 linctrl03 systemd[1]: drbd-demote-or-escalate@linstor_db.service: Succeeded.
> Dec 15 11:25:51 linctrl03 systemd[1]: Finished Demotion of DRBD resource linstor_db.
> Dec 15 11:25:59 linctrl03 kernel: drbd linstor_db linctrl02: Preparing remote state change 2634231081
> Dec 15 11:25:59 linctrl03 kernel: drbd linstor_db linctrl02: Committing remote state change 2634231081 (primary_nodes=0)
> Dec 15 11:25:59 linctrl03 kernel: drbd linstor_db linctrl02: peer( Primary -> Secondary )
> Dec 15 11:25:59 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] run: resource 'linstor_db' may promote after 0ms
> Dec 15 11:25:59 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_start: systemctl start drbd-services@linstor_db.target
> Dec 15 11:25:59 linctrl03 systemd[1]: Starting Promotion of DRBD resource linstor_db...
> Dec 15 11:25:59 linctrl03 kernel: drbd linstor_db linctrl02: Preparing remote state change 100716824
> Dec 15 11:25:59 linctrl03 kernel: drbd linstor_db linctrl02: Committing remote state change 100716824 (primary_nodes=2)
> Dec 15 11:25:59 linctrl03 kernel: drbd linstor_db linctrl02: peer( Secondary -> Primary )
> Dec 15 11:26:00 linctrl03 drbd-linstor_db[7620]: linstor_db: State change failed: (-1) Multiple primaries not allowed by config
> Dec 15 11:26:00 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Main process exited, code=exited, status=11/n/a
> Dec 15 11:26:00 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Failed with result 'exit-code'.
> Dec 15 11:26:00 linctrl03 systemd[1]: Failed to start Promotion of DRBD resource linstor_db.
> Dec 15 11:26:00 linctrl03 systemd[1]: Dependency failed for drbd-reactor controlled var-lib-linstor.
> Dec 15 11:26:00 linctrl03 drbd-reactor[7619]: A dependency job for drbd-services@linstor_db.target failed. See 'journalctl -xe' for details.
> Dec 15 11:26:00 linctrl03 systemd[1]: Dependency failed for Services for DRBD resource linstor_db.
> Dec 15 11:26:00 linctrl03 systemd[1]: drbd-services@linstor_db.target: Job drbd-services@linstor_db.target/start failed with result 'dependency'.
> Dec 15 11:26:00 linctrl03 systemd[1]: Dependency failed for drbd-reactor controlled linstor-controller.
> Dec 15 11:26:00 linctrl03 systemd[1]: linstor-controller.service: Job linstor-controller.service/start failed with result 'dependency'.
> Dec 15 11:26:00 linctrl03 systemd[1]: var-lib-linstor.mount: Job var-lib-linstor.mount/start failed with result 'dependency'.
> Dec 15 11:26:00 linctrl03 systemd[1]: drbd-promote@linstor_db.service: Triggering OnFailure= dependencies.
> Dec 15 11:26:00 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] stop_actions (could trigger failure actions (e.g., reboot)): linstor_db
> Dec 15 11:26:00 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] stop_actions: stopping 'drbd-services@linstor_db.target'
> Dec 15 11:26:00 linctrl03 systemd[1]: Starting Demotion of DRBD resource linstor_db...
> Dec 15 11:26:00 linctrl03 drbd-linstor_db[7631]: about to demote (or escalate to the FailureAction)
> Dec 15 11:26:00 linctrl03 drbd-reactor[733]: INFO [drbd_reactor::plugin::promoter] systemd_stop: systemctl stop drbd-services@linstor_db.target
> Dec 15 11:26:00 linctrl03 systemd[1]: drbd-demote-or-escalate@linstor_db.service: Succeeded.
> Dec 15 11:26:00 linctrl03 systemd[1]: Finished Demotion of DRBD resource linstor_db.
> Dec 15 11:26:00 linctrl03 sshd[7642]: Accepted publickey for root from 10.10.12.8 port 57524 ssh2: RSA SHA256:I2+1ZwpwbgQP/izgNkR6QcvBkUVvBa+YxKjYokgeG9I
> Dec 15 11:26:00 linctrl03 sshd[7642]: pam_unix(sshd:session): session opened for user root by (uid=0)
> Dec 15 11:26:00 linctrl03 systemd-logind[692]: New session 34 of user root.
> Dec 15 11:26:00 linctrl03 systemd[1]: Started Session 34 of user root.
> Dec 15 11:26:01 linctrl03 systemd[1]: Reloading DRBD-Reactor Service.
> Dec 15 11:26:01 linctrl03 systemd[1]: Reloaded DRBD-Reactor Service.
> Dec 15 11:26:01 linctrl03 sshd[7642]: Received disconnect from 10.10.12.8 port 57524:11: disconnected by user
> Dec 15 11:26:01 linctrl03 sshd[7642]: Disconnected from user root 10.10.12.8 port 57524
> Dec 15 11:26:01 linctrl03 sshd[7642]: pam_unix(sshd:session): session closed for user root
> Dec 15 11:26:01 linctrl03 systemd[1]: session-34.scope: Succeeded.
> Dec 15 11:26:01 linctrl03 systemd-logind[692]: Session 34 logged out. Waiting for processes to exit.
> Dec 15 11:26:01 linctrl03 systemd-logind[692]: Removed session 34.
> Dec 15 11:26:07 linctrl03 kernel: drbd linstor_db linctrl02: Preparing remote state change 2041306110
> Dec 15 11:26:07 linctrl03 kernel: drbd linstor_db linctrl02: Committing remote state change 2041306110 (primary_nodes=0)
> Dec 15 11:26:07 linctrl03 kernel: drbd linstor_db linctrl02: peer( Primary -> Secondary )

**Comment by rck** [comment]
hm, I don't think this is a general problem, at least everything looks fine for me. what you could do:

- `systemctl disable drbd-reactor.service` on all nodes
- `systemclt stop drbd-services@linstor_db.target` on all nodes
- `drbdsetup status` to check if the resources is Secondary on all nodes
- on one node: `systemctl start drbd-services@linstor_db.target` and check with `drbdsetup status` if it came up/is primary and FS mounted and controller started. If not, collect the logs and attach to this ticket
- if the above worked, stop the target again and `systemctl start drbd-reactor.service` on 1 node and check if everthing came up. If not, collect the logs.

Just from the logs above I'm not sure if things really went wrong and where. It is expected that target start fails and things complain about dependencies. That is expected on all nodes except the one that succeeds. But I guess you know that, please just try with 1 node and check if things work there.

**Comment by WanzenBug** [comment]
Random note: you probably want to upgrade to LINSTOR 1.20.2, as 1.20.1 has an issue with database migrations.

**Comment by rck** [comment]
speaking of logs: even when reactor is disabled, you can run certain `drbd-reactorctl` commands, `status` being one of them. So `drbd-reactorctl status --verbose linstor_db` might be helpful for log collecting.

**Comment by acidrop** [comment]
Well, after some further digging I realized that the reason that reactor is failing to bring up controller is because of a corrupted db..

```
> Caused by:
==========

Category:                           RuntimeException
Class name:                         IllegalStateException
Class canonical name:               java.lang.IllegalStateException
Generated at:                       Method 'newIllegalStateException', Source file 'DataUtils.java', Line #870

Error message:                      File corrupted in chunk 104211, expected page length 4..512, got 100689399 [1.4.197/6]
```

I've restored the db from a previous checkpoint and it seems to be ok now. I'm testing via 'drbd-reactorctl evict' method.
I've updated to the latest controller version too (1.20.2). It's still strange though that I could manually mount the linstor_db drbd resource (at least on some of the nodes). Wondering if the db corrupted itself during reactor attempts to evict the service on a different node ? (i.e umount /var/lib/linstor forcefully)
